"""
BharatConnect Theme & Design System Facade (app/theme.py)
Re-exports all core color tokens, gradient components, and UI widgets from utils/helper.py
"""

from utils.helper import (
    COLOR_6367FF,
    COLOR_8494FF,
    COLOR_C9BEFF,
    COLOR_FFDBFD,
    COLOR_2F2FE4,
    COLOR_162E93,
    COLOR_1A1953,
    COLOR_080616,
    COLOR_TEXT_MAIN,
    COLOR_TEXT_MUTED,
    COLOR_TEXT_SUBTLE,
    COLOR_EMERALD,
    COLOR_AMBER,
    create_gradient_texture,
    create_vibrant_3stop_gradient,
    hex_to_rgba,
    parse_kivy_radius,
    GradientCard,
    GradientBox,
    GlassCard,
    create_pill_badge,
    create_avatar_widget,
    create_story_avatar_widget,
    create_verified_badge,
    create_icon_button,
    create_primary_button,
    create_outlined_button,
)

__all__ = [
    "COLOR_6367FF",
    "COLOR_8494FF",
    "COLOR_C9BEFF",
    "COLOR_FFDBFD",
    "COLOR_2F2FE4",
    "COLOR_162E93",
    "COLOR_1A1953",
    "COLOR_080616",
    "COLOR_TEXT_MAIN",
    "COLOR_TEXT_MUTED",
    "COLOR_TEXT_SUBTLE",
    "COLOR_EMERALD",
    "COLOR_AMBER",
    "create_gradient_texture",
    "create_vibrant_3stop_gradient",
    "hex_to_rgba",
    "parse_kivy_radius",
    "GradientCard",
    "GradientBox",
    "GlassCard",
    "create_pill_badge",
    "create_avatar_widget",
    "create_story_avatar_widget",
    "create_verified_badge",
    "create_icon_button",
    "create_primary_button",
    "create_outlined_button",
]

